### ISSUE TITLE
Splunk user and splunk group should (probably) not be created by Ansible when using Red Hat RPM.

### ISSUE THREAD

**Issue by bschonec** [AustinCloudGuru/ansible-role-splunk-forwarder#16]
In the splunkforwarder RPM install scripts, the group splunk and user splunk are created.  While the script does take into account the preexisting condition of the group/user being created, would it not be better to let the RPM handle those tasks so that the UID and GID of the user/group are set to what Splunk (the company) want them to be?

**Comment by AustinCloudGuru** [comment]
Unlike ports, UID and GID are not set by companies/applications.  When the RPM creates the user, it just grabs the next available UID/GID and creates the user/group with those.  If it didn't, installs would fail if a specific UID/GID already existed.  Personally, (opinionated to be sure), I prefer to control what UID and GID are used for each service account so that they are consistent across systems.  Otherwise the splunk user might be UID 1004 on one server, UID 1009 on another, etc, and that would just be chaos :)
